version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - npm install -g gatsby
            - npm install
    build:
        commands:
            - npm run test
            - npm run build
artifacts:
    files:
        - "**/*"
    base-directory: public
